### ISSUE TITLE
SyntaxError: non-default argument follows default argument

### ISSUE THREAD

**Issue by z2labplus** [zilliz-bootcamp/video_analysis#3]
When I run the python main.py ，it catch the error
  File "main.py", line 167
    async def get_face_info(time: int, table_name: str=None, request: Request, filename: str):                
                           ^
SyntaxError: non-default argument follows default argument
(/data/share/anaconda-envs/video) [root@qn66 webservice]# python main.py                                      
  File "main.py", line 166
    async def get_face_info(table_name: str = None, request: Request, filename: str, time: int):              
                           ^
SyntaxError: non-default argument follows default argument
My python version is Python 3.7.10

**Comment by miia12** [comment]
Try to keep the original parameter order. https://stackoverflow.com/questions/24719368/syntaxerror-non-default-argument-follows-default-argument/39942121

**Comment by z2labplus** [comment]
when i change to
async def get_face_info(request: Request, filename: str, time: int, table_name: str=None):
it works  amazing

**Comment by miia12** [comment]
Solved
